apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-big-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eyupyayan/Kubernetes-Project.git
    targetRevision: master
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-big
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
