apiVersion: v1
kind: Service
metadata:
  name: k8s-big-app
  namespace: k8s-big
spec:
  selector:
    app: k8s-big-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
